name: Publish Docker Image

on:
  push:
    paths:
      - "**DockerfileMaven**"

env:
  REGISTRY: useast.jfrog.lexisnexisrisk.com
  IMAGE_NAME: SDET_Java_Maven

jobs:
  Package_build:
    runs-on: on-prem
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build the Docker Image
        run: docker build . --file DockerfileMaven --tag ${{ env.IMAGE_NAME }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Login to JFrog Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.Jfrog_username }}  #TODO -> create in Github
          password: ${{ secrets.Jfrog_token }}     # TODO -> create token in jfrog

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Tag and Push
        run: |
          docker tag ${{ env.IMAGE_NAME }} "${{ env.REGISTRY }}/sdet-java-maven-framework-docker-image/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}"
          docker push "${{ env.REGISTRY }}/sdet-java-maven-framework-docker-image/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}"
