# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: check the directory
      run: pwd
    - name: list the contents
      run: ls -latr
#    - name: install chrome on VM
#      uses: browser-actions/setup-chrome@latest
#    - name: check the chrome version
#      run: chrome --version
    - name: change directory
      run: cd TAF/
    - name: Build with Maven
      working-directory: TAF/
      run: |
        ls -latr
        mvn clean
        ls-latr
    - name: upload artifacts to github
      uses: actions/upload-artifact@master
      with:
        name: Artifacts for TAF
        path: TAF
        if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: Artifacts for TAF
          path: TAF
      - name: maven test
        working-directory: TAF/
        run: |
          mvn test
        env:
          CI: true